### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [jonnybest/SmartShutdown#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by jonnybest** [comment]
Hey, thanks for the info.

**Comment by jonnybest** [comment]
Fixed in 21e6d74f05c5e0cd7b10118b1a9e28dcaa8532d5. Thanks for caring!
